import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import { UserProvider } from "@/contexts/AuthContextProvider";
import { NextUIProvider } from "@nextui-org/react";
import { Providers } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " min-h-[100vh] flex flex-col"}>
        <Providers>
          <div className="flex-1">
            <NavBar />
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
